import { ENDPOINT_TYPE, objectValues } from '@shared/data/types/model';
import * as z from 'zod';

export const CONFIGURE_BUILTIN_PROVIDER_TOOL_NAME = 'configure_builtin_provider';
export const CREATE_CUSTOM_PROVIDER_TOOL_NAME = 'create_custom_provider';

export const PROVIDER_CONFIGURATION_TOOL_NAMES = [
  CONFIGURE_BUILTIN_PROVIDER_TOOL_NAME,
  CREATE_CUSTOM_PROVIDER_TOOL_NAME,
] as const;

export type ProviderConfigurationToolName = (typeof PROVIDER_CONFIGURATION_TOOL_NAMES)[number];

export const PROVIDER_CONFIGURATION_INTENTS = [
  'configure',
  'models',
  'configure-and-models',
] as const;
export const ProviderConfigurationIntentSchema = z.enum(PROVIDER_CONFIGURATION_INTENTS);

const manualModelSchema = z
  .object({
    contextWindow: z.number().int().nonnegative(),
    endpointTypes: z.array(z.enum(objectValues(ENDPOINT_TYPE))).max(8),
    group: z.string().max(200),
    maxInputTokens: z.number().int().nonnegative(),
    maxOutputTokens: z.number().int().nonnegative(),
    modelId: z.string().trim().min(1).max(500),
    name: z.string().trim().max(500),
  })
  .strict();

const modelDraftFields = {
  manualModels: z
    .array(manualModelSchema)
    .max(500)
    .describe('Manually added model drafts. Pass an empty array when none are requested.'),
  removedModelIds: z
    .array(z.string().trim().min(1).max(1000))
    .max(5000)
    .describe(
      'Existing model unique ids explicitly selected for removal. Pass an empty array otherwise.',
    ),
  selectedModelIds: z
    .array(z.string().trim().min(1).max(1000))
    .max(5000)
    .describe(
      'Fresh catalog model unique ids selected for addition. Pass an empty array before review.',
    ),
  skipModelPull: z
    .boolean()
    .describe(
      'Pass true only when the user explicitly saves after catalog loading failed or skips models.',
    ),
};

/** Strict AI-SDK input. Empty strings/arrays represent fields the model does not know yet. */
export const configureBuiltinProviderInputSchema = z
  .object({
    apiKey: z
      .string()
      .max(20_000)
      .describe('API key supplied by the user. Pass an empty string when absent.'),
    baseUrl: z
      .string()
      .trim()
      .max(4000)
      .describe(
        'Requested Base URL override. Pass an empty string to preserve the current endpoint.',
      ),
    intent: ProviderConfigurationIntentSchema.describe(
      'configure for credentials/endpoints, models for pull/add only, or configure-and-models for both.',
    ),
    provider: z
      .string()
      .trim()
      .max(500)
      .describe(
        'Built-in provider id or name. Pass an empty string when the user did not specify one.',
      ),
    ...modelDraftFields,
  })
  .strict();

/** Strict AI-SDK input. providerId is generated by the review sheet and must initially be empty. */
export const createCustomProviderInputSchema = z
  .object({
    anthropicUrl: z.string().trim().max(4000),
    apiKey: z.string().max(20_000),
    baseUrl: z.string().trim().max(4000),
    defaultChatEndpoint: z.enum([
      ENDPOINT_TYPE.OPENAI_CHAT_COMPLETIONS,
      ENDPOINT_TYPE.OPENAI_RESPONSES,
      ENDPOINT_TYPE.ANTHROPIC_MESSAGES,
      ENDPOINT_TYPE.GOOGLE_GENERATE_CONTENT,
    ]),
    geminiUrl: z.string().trim().max(4000),
    imageEditUrl: z.string().trim().max(4000),
    imageGenerationUrl: z.string().trim().max(4000),
    intent: ProviderConfigurationIntentSchema,
    name: z.string().trim().max(500),
    openaiResponsesUrl: z.string().trim().max(4000),
    providerId: z
      .string()
      .trim()
      .max(200)
      .describe(
        'Pass an empty string initially. The review sheet generates a stable id before approval.',
      ),
    ...modelDraftFields,
  })
  .strict();

export const providerConfigurationSummarySchema = z
  .object({
    apiKeyAdded: z.boolean(),
    catalogSource: z.enum(['api', 'registry', 'skipped']),
    modelsAdded: z.array(z.string()),
    modelsRemoved: z.array(z.string()),
    modelsSkipped: z.array(z.string()),
    origin: z.string(),
    providerId: z.string(),
    providerName: z.string(),
    status: z.literal('configured'),
  })
  .strict();

export const providerConfigurationResolutionSchema = z
  .object({
    candidates: z.array(z.object({ id: z.string(), name: z.string() }).strict()),
    message: z.string(),
    status: z.enum(['ambiguous', 'disabled', 'invalid', 'not-found', 'provider-required']),
  })
  .strict();

export const providerConfigurationToolOutputSchema = z.union([
  providerConfigurationSummarySchema,
  providerConfigurationResolutionSchema,
]);

export type ConfigureBuiltinProviderInput = z.infer<typeof configureBuiltinProviderInputSchema>;
export type CreateCustomProviderInput = z.infer<typeof createCustomProviderInputSchema>;
export type ProviderConfigurationManualModel = z.infer<typeof manualModelSchema>;
export type ProviderConfigurationSummary = z.infer<typeof providerConfigurationSummarySchema>;
export type ProviderConfigurationResolution = z.infer<typeof providerConfigurationResolutionSchema>;
export type ProviderConfigurationToolOutput = z.infer<typeof providerConfigurationToolOutputSchema>;

export function isProviderConfigurationToolName(
  value: string,
): value is ProviderConfigurationToolName {
  return PROVIDER_CONFIGURATION_TOOL_NAMES.some((name) => name === value);
}
