/**
 * Curated catalog of vendor-hosted remote MCP servers.
 *
 * Mobile connects to remote Streamable-HTTP / SSE endpoints only: a server that
 * must run as a local process (filesystem, git, postgres, puppeteer, …) cannot
 * be reached from a phone and is deliberately absent. Every entry below is a
 * first-party, publicly documented endpoint; `source` records where the endpoint
 * and its auth model were taken from so a reviewer can re-verify it.
 *
 * This is the "expand the plugins list" surface: adding a hosted server is a
 * data entry here, not a new module. `createCatalogPlugin` turns each entry into
 * a real, registered `PluginDefinition`.
 */

export type McpCatalogCategory =
  | 'dev-tools'
  | 'cloud'
  | 'databases'
  | 'productivity'
  | 'design'
  | 'communication'
  | 'crm'
  | 'marketing'
  | 'finance'
  | 'analytics'
  | 'search'
  | 'scraping'
  | 'ai'
  | 'media'
  | 'lifestyle';

export type McpCatalogAuth =
  | { readonly kind: 'oauth'; readonly label: string; readonly scopes?: readonly string[] }
  | { readonly kind: 'bearer'; readonly label: string; readonly credentialsUrl: string }
  | {
      readonly kind: 'api-key';
      readonly header: string;
      readonly label: string;
      readonly credentialsUrl: string;
    }
  | { readonly kind: 'none' };

export type McpCatalogEntry = {
  /** Stable slug; must satisfy the plugin id grammar (`^[a-z][a-z0-9]*(?:[-_.][a-z0-9]+)*$`). */
  readonly id: string;
  readonly name: string;
  readonly summary: string;
  readonly category: McpCatalogCategory;
  /** Complete MCP endpoint URL (Streamable HTTP preferred; `/sse` where the vendor only publishes SSE). */
  readonly endpointUrl: string;
  /** Advertised authorization options, most-preferred first. */
  readonly auth: readonly McpCatalogAuth[];
  readonly website: string;
  readonly privacy: string;
  readonly icon?: string;
  /** Provenance for the endpoint and auth model. */
  readonly source: string;
};

const oauth = (label: string, scopes?: readonly string[]): McpCatalogAuth =>
  scopes ? { kind: 'oauth', label, scopes } : { kind: 'oauth', label };
const bearer = (label: string, credentialsUrl: string): McpCatalogAuth => ({
  kind: 'bearer',
  label,
  credentialsUrl,
});
const NONE: McpCatalogAuth = { kind: 'none' };

export const mcpServerCatalog: readonly McpCatalogEntry[] = [
  // ── Dev tools ────────────────────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    summary: 'Repositories, issues, pull requests, Actions and code search.',
    category: 'dev-tools',
    endpointUrl: 'https://api.githubcopilot.com/mcp/',
    auth: [
      oauth('Sign in with GitHub'),
      bearer('Personal access token', 'https://github.com/settings/personal-access-tokens/new'),
    ],
    website: 'https://github.com',
    privacy:
      'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement',
    icon: 'github',
    source: 'https://docs.github.com/en/copilot/customizing-copilot/using-model-context-protocol',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    summary: 'Projects, merge requests and issues from your GitLab instance.',
    category: 'dev-tools',
    endpointUrl: 'https://gitlab.com/api/v4/mcp',
    auth: [
      oauth('Sign in with GitLab'),
      bearer('Personal access token', 'https://gitlab.com/-/user_settings/personal_access_tokens'),
    ],
    website: 'https://gitlab.com',
    privacy: 'https://about.gitlab.com/privacy/',
    source: 'https://docs.gitlab.com/user/gitlab_duo/model_context_protocol/',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    summary: 'Search errors, read performance data and triage issues.',
    category: 'dev-tools',
    endpointUrl: 'https://mcp.sentry.dev/mcp',
    auth: [oauth('Sign in with Sentry')],
    website: 'https://sentry.io',
    privacy: 'https://sentry.io/privacy/',
    source: 'https://docs.sentry.io/product/sentry-mcp/',
  },
  {
    id: 'linear',
    name: 'Linear',
    summary: 'Find, create and update issues, projects and comments.',
    category: 'dev-tools',
    endpointUrl: 'https://mcp.linear.app/mcp',
    auth: [
      oauth('Sign in with Linear'),
      bearer('Linear API key', 'https://linear.app/settings/account/security'),
    ],
    website: 'https://linear.app',
    privacy: 'https://linear.app/privacy',
    source: 'https://linear.app/docs/mcp',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    summary: 'Deployments, projects and logs across your Vercel account.',
    category: 'dev-tools',
    endpointUrl: 'https://mcp.vercel.com',
    auth: [oauth('Sign in with Vercel')],
    website: 'https://vercel.com',
    privacy: 'https://vercel.com/legal/privacy-policy',
    source: 'https://vercel.com/docs/mcp/vercel-mcp',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    summary: 'Create, deploy and manage sites and serverless functions.',
    category: 'dev-tools',
    endpointUrl: 'https://netlify-mcp.netlify.app/mcp',
    auth: [oauth('Sign in with Netlify')],
    website: 'https://netlify.com',
    privacy: 'https://www.netlify.com/privacy/',
    source: 'https://docs.netlify.com/build/ai/mcp-server/',
  },
  {
    id: 'railway',
    name: 'Railway',
    summary: 'Projects, services, environments and deployments.',
    category: 'dev-tools',
    endpointUrl: 'https://mcp.railway.com',
    auth: [oauth('Sign in with Railway')],
    website: 'https://railway.com',
    privacy: 'https://railway.com/legal/privacy',
    source: 'https://docs.railway.com/guides/mcp',
  },
  {
    id: 'buildkite',
    name: 'Buildkite',
    summary: 'CI/CD pipelines, builds and agents.',
    category: 'dev-tools',
    endpointUrl: 'https://mcp.buildkite.com/mcp',
    auth: [oauth('Sign in with Buildkite')],
    website: 'https://buildkite.com',
    privacy: 'https://buildkite.com/legal/privacy-policy',
    source: 'https://buildkite.com/docs/apis/mcp-server',
  },
  {
    id: 'neon',
    name: 'Neon',
    summary: 'Manage and query your serverless Postgres databases.',
    category: 'databases',
    endpointUrl: 'https://mcp.neon.tech/mcp',
    auth: [oauth('Sign in with Neon')],
    website: 'https://neon.tech',
    privacy: 'https://neon.tech/privacy-policy',
    source: 'https://neon.com/docs/ai/neon-mcp-server',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    summary: 'Query your database, inspect schema and manage projects.',
    category: 'databases',
    endpointUrl: 'https://mcp.supabase.com/mcp',
    auth: [
      oauth('Sign in with Supabase'),
      bearer('Personal access token', 'https://supabase.com/dashboard/account/tokens'),
    ],
    website: 'https://supabase.com',
    privacy: 'https://supabase.com/privacy',
    source: 'https://supabase.com/docs/guides/ai-tools/mcp',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    summary: 'Database ORM, migrations and schema tooling.',
    category: 'databases',
    endpointUrl: 'https://mcp.prisma.io/mcp',
    auth: [oauth('Sign in with Prisma')],
    website: 'https://www.prisma.io',
    privacy: 'https://www.prisma.io/privacy',
    source: 'https://www.prisma.io/docs/ai/tools/mcp-server',
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse Cloud',
    summary: 'Query and explore your ClickHouse Cloud services.',
    category: 'databases',
    endpointUrl: 'https://mcp.clickhouse.cloud/mcp',
    auth: [oauth('Sign in with ClickHouse Cloud')],
    website: 'https://clickhouse.com',
    privacy: 'https://clickhouse.com/legal/privacy-policy',
    source: 'https://clickhouse.com/docs/use-cases/AI/MCP/cloud',
  },
  {
    id: 'grafbase',
    name: 'Grafbase',
    summary: 'GraphQL backend, schema and deployment tooling.',
    category: 'databases',
    endpointUrl: 'https://api.grafbase.com/mcp',
    auth: [oauth('Sign in with Grafbase')],
    website: 'https://grafbase.com',
    privacy: 'https://grafbase.com/privacy',
    source: 'https://grafbase.com/docs/mcp',
  },
  {
    id: 'mongodb-atlas',
    name: 'MongoDB Atlas',
    summary: 'Query MongoDB databases and Atlas tooling.',
    category: 'databases',
    endpointUrl: 'https://mcp.mongodb.com/mcp',
    auth: [
      oauth('Sign in with MongoDB Atlas'),
      bearer('Atlas API key', 'https://www.mongodb.com/docs/atlas/configure-api-access/'),
    ],
    website: 'https://www.mongodb.com',
    privacy: 'https://www.mongodb.com/legal/privacy-policy',
    source: 'https://www.mongodb.com/docs/mcp-server/',
  },
  // ── Cloud / infra ────────────────────────────────────────────────────────
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    summary: 'Workers, D1, R2, DNS and account APIs via Code Mode.',
    category: 'cloud',
    endpointUrl: 'https://mcp.cloudflare.com/mcp',
    auth: [
      oauth('Sign in with Cloudflare'),
      bearer('Cloudflare API token', 'https://dash.cloudflare.com/profile/api-tokens'),
    ],
    website: 'https://cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'cloudflare-docs',
    name: 'Cloudflare Docs',
    summary: 'Up-to-date Cloudflare reference documentation.',
    category: 'cloud',
    endpointUrl: 'https://docs.mcp.cloudflare.com/mcp',
    auth: [NONE],
    website: 'https://developers.cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'cloudflare-observability',
    name: 'Cloudflare Observability',
    summary: 'Debug logs and analytics for your applications.',
    category: 'cloud',
    endpointUrl: 'https://observability.mcp.cloudflare.com/mcp',
    auth: [oauth('Sign in with Cloudflare')],
    website: 'https://developers.cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'cloudflare-bindings',
    name: 'Cloudflare Workers Bindings',
    summary: 'Build Workers with storage, AI and compute primitives.',
    category: 'cloud',
    endpointUrl: 'https://bindings.mcp.cloudflare.com/mcp',
    auth: [oauth('Sign in with Cloudflare')],
    website: 'https://developers.cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'cloudflare-radar',
    name: 'Cloudflare Radar',
    summary: 'Explore Cloudflare Radar internet insights.',
    category: 'cloud',
    endpointUrl: 'https://radar.mcp.cloudflare.com/mcp',
    auth: [oauth('Sign in with Cloudflare')],
    website: 'https://radar.cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'cloudflare-browser',
    name: 'Cloudflare Browser Rendering',
    summary: 'Fetch web pages, convert them to markdown and screenshot.',
    category: 'cloud',
    endpointUrl: 'https://browser.mcp.cloudflare.com/mcp',
    auth: [oauth('Sign in with Cloudflare')],
    website: 'https://developers.cloudflare.com',
    privacy: 'https://www.cloudflare.com/privacypolicy/',
    source: 'https://github.com/cloudflare/mcp-server-cloudflare',
  },
  {
    id: 'hostinger',
    name: 'Hostinger',
    summary: 'Hosting, VPS, WordPress, domains and DNS.',
    category: 'cloud',
    endpointUrl: 'https://mcp.hostinger.com/mcp',
    auth: [bearer('Hostinger API token', 'https://hpanel.hostinger.com/api')],
    website: 'https://hostinger.com',
    privacy: 'https://www.hostinger.com/privacy-policy',
    source: 'https://github.com/hostinger/api-mcp-server',
  },
  {
    id: 'aiven',
    name: 'Aiven',
    summary: 'Managed data infrastructure across clouds.',
    category: 'cloud',
    endpointUrl: 'https://mcp.aiven.live/mcp',
    auth: [oauth('Sign in with Aiven')],
    website: 'https://aiven.io',
    privacy: 'https://aiven.io/privacy',
    source: 'https://aiven.io/docs/tools/mcp',
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    summary: 'Backend platform: databases, auth, storage and functions.',
    category: 'cloud',
    endpointUrl: 'https://mcp.appwrite.io/mcp',
    auth: [oauth('Sign in with Appwrite')],
    website: 'https://appwrite.io',
    privacy: 'https://appwrite.io/privacy',
    source: 'https://appwrite.io/docs/tooling/mcp',
  },
  // ── Productivity / knowledge ─────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    summary: 'Search pages and databases and draft content in your workspace.',
    category: 'productivity',
    endpointUrl: 'https://mcp.notion.com/mcp',
    auth: [oauth('Sign in with Notion')],
    website: 'https://www.notion.com',
    privacy: 'https://www.notion.com/privacy',
    icon: 'notion',
    source: 'https://developers.notion.com/docs/mcp',
  },
  {
    id: 'atlassian',
    name: 'Atlassian (Jira & Confluence)',
    summary: 'Search and update Jira issues, Confluence pages and Bitbucket.',
    category: 'productivity',
    endpointUrl: 'https://mcp.atlassian.com/v2/mcp',
    auth: [oauth('Sign in with Atlassian')],
    website: 'https://www.atlassian.com',
    privacy: 'https://www.atlassian.com/legal/privacy-policy',
    source:
      'https://support.atlassian.com/rovo/docs/getting-started-with-the-atlassian-remote-mcp-server/',
  },
  {
    id: 'asana',
    name: 'Asana',
    summary: 'Tasks, projects, sections and portfolios from the Asana Work Graph.',
    category: 'productivity',
    endpointUrl: 'https://mcp.asana.com/v2/mcp',
    auth: [oauth('Sign in with Asana')],
    website: 'https://asana.com',
    privacy: 'https://asana.com/terms#privacy-statement',
    source: 'https://developers.asana.com/docs/using-asanas-model-context-protocol-mcp-server',
  },
  {
    id: 'monday',
    name: 'monday.com',
    summary: 'Boards, items and updates from your monday.com workspace.',
    category: 'productivity',
    endpointUrl: 'https://mcp.monday.com/mcp',
    auth: [oauth('Sign in with monday.com')],
    website: 'https://monday.com',
    privacy: 'https://monday.com/l/privacy/privacy-policy/',
    source: 'https://developer.monday.com/apps/docs/mondaycom-mcp',
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    summary: 'Tasks, docs and spaces across your ClickUp workspace.',
    category: 'productivity',
    endpointUrl: 'https://mcp.clickup.com/mcp',
    auth: [oauth('Sign in with ClickUp')],
    website: 'https://clickup.com',
    privacy: 'https://clickup.com/privacy',
    source: 'https://developer.clickup.com/docs/mcp',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    summary: 'Create, search and complete tasks and projects.',
    category: 'productivity',
    endpointUrl: 'https://ai.todoist.net/mcp',
    auth: [oauth('Sign in with Todoist')],
    website: 'https://todoist.com',
    privacy: 'https://doist.com/privacy',
    source: 'https://www.todoist.com/help/articles/use-todoist-with-ai-assistants',
  },
  {
    id: 'miro',
    name: 'Miro',
    summary: 'Read and create diagrams, notes and frames on your boards.',
    category: 'design',
    endpointUrl: 'https://mcp.miro.com/',
    auth: [oauth('Sign in with Miro')],
    website: 'https://miro.com',
    privacy: 'https://miro.com/legal/privacy-policy/',
    source: 'https://developers.miro.com/docs/miro-mcp',
  },
  {
    id: 'figma',
    name: 'Figma',
    summary: 'Pull design files, frames and specs into build-ready context.',
    category: 'design',
    endpointUrl: 'https://mcp.figma.com/mcp',
    auth: [oauth('Sign in with Figma')],
    website: 'https://figma.com',
    privacy: 'https://www.figma.com/legal/privacy/',
    source: 'https://help.figma.com/hc/en-us/articles/32132100833559-Guide-to-the-Figma-MCP-server',
  },
  {
    id: 'canva',
    name: 'Canva',
    summary: 'Generate and edit designs — graphics, docs and presentations.',
    category: 'design',
    endpointUrl: 'https://mcp.canva.com/mcp',
    auth: [oauth('Sign in with Canva')],
    website: 'https://canva.com',
    privacy: 'https://www.canva.com/policies/privacy-policy/',
    source: 'https://www.canva.dev/docs/mcp/',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    summary: 'Read and update sites, pages and CMS content.',
    category: 'design',
    endpointUrl: 'https://mcp.webflow.com/mcp',
    auth: [oauth('Sign in with Webflow')],
    website: 'https://webflow.com',
    privacy: 'https://webflow.com/legal/privacy',
    source: 'https://developers.webflow.com/data/docs/mcp',
  },
  {
    id: 'wix',
    name: 'Wix',
    summary: 'Manage your Wix site — content, bookings and products.',
    category: 'design',
    endpointUrl: 'https://mcp.wix.com/mcp',
    auth: [oauth('Sign in with Wix')],
    website: 'https://wix.com',
    privacy: 'https://www.wix.com/about/privacy',
    source: 'https://dev.wix.com/docs/sdk/articles/use-the-wix-mcp',
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    summary: 'Create and edit hand-drawn style diagrams.',
    category: 'design',
    endpointUrl: 'https://api.excalidraw.com/api/v1/mcp',
    auth: [oauth('Sign in with Excalidraw')],
    website: 'https://excalidraw.com',
    privacy: 'https://plus.excalidraw.com/legal/privacy',
    source: 'https://plus.excalidraw.com/docs/mcp',
  },
  {
    id: 'lucid',
    name: 'Lucidchart',
    summary: 'Create and edit Lucid diagrams and documents.',
    category: 'design',
    endpointUrl: 'https://mcp.lucid.app/mcp',
    auth: [oauth('Sign in with Lucid')],
    website: 'https://lucid.co',
    privacy: 'https://lucid.co/privacy',
    source: 'https://developer.lucid.co/docs/mcp',
  },
  {
    id: 'higgsfield',
    name: 'Higgsfield',
    summary: 'Generate cinematic AI images and videos.',
    category: 'media',
    endpointUrl: 'https://mcp.higgsfield.ai/mcp',
    auth: [oauth('Sign in with Higgsfield')],
    website: 'https://higgsfield.ai',
    privacy: 'https://higgsfield.ai/privacy',
    source: 'https://higgsfield.ai/mcp',
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    summary: 'Media management, transformation and optimization.',
    category: 'media',
    endpointUrl: 'https://asset-management.mcp.cloudinary.com/mcp',
    auth: [oauth('Sign in with Cloudinary')],
    website: 'https://cloudinary.com',
    privacy: 'https://cloudinary.com/privacy',
    source: 'https://cloudinary.com/documentation/cloudinary_mcp_server',
  },
  // ── Communication ────────────────────────────────────────────────────────
  {
    id: 'slack',
    name: 'Slack',
    summary: 'Search messages, post to channels and read your workspace.',
    category: 'communication',
    endpointUrl: 'https://mcp.slack.com/mcp',
    auth: [oauth('Sign in with Slack')],
    website: 'https://slack.com',
    privacy: 'https://slack.com/trust/privacy/privacy-policy',
    source: 'https://docs.slack.dev/mcp/',
  },
  {
    id: 'intercom',
    name: 'Intercom',
    summary: 'Conversations, contacts and help content.',
    category: 'communication',
    endpointUrl: 'https://mcp.intercom.com/mcp',
    auth: [oauth('Sign in with Intercom')],
    website: 'https://intercom.com',
    privacy: 'https://www.intercom.com/legal/privacy',
    source: 'https://developers.intercom.com/docs/guides/mcp',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    summary: 'Meetings, recordings and scheduling across Zoom.',
    category: 'communication',
    endpointUrl: 'https://mcp.zoom.us/mcp/zoom/streamable',
    auth: [oauth('Sign in with Zoom')],
    website: 'https://zoom.us',
    privacy: 'https://explore.zoom.us/en/privacy/',
    source: 'https://developers.zoom.us/docs/mcp/',
  },
  {
    id: 'telnyx',
    name: 'Telnyx',
    summary: 'Communications APIs — messaging, voice and numbers.',
    category: 'communication',
    endpointUrl: 'https://api.telnyx.com/v2/mcp',
    auth: [bearer('Telnyx API key', 'https://portal.telnyx.com/#/app/api-keys')],
    website: 'https://telnyx.com',
    privacy: 'https://telnyx.com/privacy-policy',
    source: 'https://developers.telnyx.com/docs/mcp',
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    summary: 'Meeting transcription, notes and summaries.',
    category: 'communication',
    endpointUrl: 'https://api.fireflies.ai/mcp',
    auth: [oauth('Sign in with Fireflies')],
    website: 'https://fireflies.ai',
    privacy: 'https://fireflies.ai/privacy',
    source: 'https://docs.fireflies.ai/getting-started/mcp',
  },
  // ── CRM / marketing ──────────────────────────────────────────────────────
  {
    id: 'hubspot',
    name: 'HubSpot',
    summary: 'Contacts, deals and marketing data from your CRM.',
    category: 'crm',
    endpointUrl: 'https://mcp.hubspot.com',
    auth: [oauth('Sign in with HubSpot')],
    website: 'https://hubspot.com',
    privacy: 'https://legal.hubspot.com/privacy-policy',
    source: 'https://developers.hubspot.com/mcp',
  },
  {
    id: 'attio',
    name: 'Attio',
    summary: 'CRM records, objects and workspace data.',
    category: 'crm',
    endpointUrl: 'https://mcp.attio.com/mcp',
    auth: [oauth('Sign in with Attio')],
    website: 'https://attio.com',
    privacy: 'https://attio.com/legal/privacy',
    source: 'https://docs.attio.com/mcp',
  },
  {
    id: 'close',
    name: 'Close',
    summary: 'CRM leads, contacts and opportunities.',
    category: 'crm',
    endpointUrl: 'https://mcp.close.com/mcp',
    auth: [oauth('Sign in with Close')],
    website: 'https://close.com',
    privacy: 'https://close.com/privacy/',
    source: 'https://developer.close.com/docs/mcp',
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    summary: 'Email marketing campaigns, profiles and analytics.',
    category: 'marketing',
    endpointUrl: 'https://mcp.klaviyo.com/mcp',
    auth: [oauth('Sign in with Klaviyo')],
    website: 'https://klaviyo.com',
    privacy: 'https://www.klaviyo.com/legal/privacy',
    source: 'https://developers.klaviyo.com/en/docs/klaviyo_mcp',
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    summary: 'Product analytics, cohorts and experiments.',
    category: 'analytics',
    endpointUrl: 'https://mcp.amplitude.com/mcp',
    auth: [oauth('Sign in with Amplitude')],
    website: 'https://amplitude.com',
    privacy: 'https://amplitude.com/privacy',
    source: 'https://amplitude.com/docs/analytics/mcp',
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    summary: 'Analyze, query and manage your Mixpanel data.',
    category: 'analytics',
    endpointUrl: 'https://mcp.mixpanel.com/mcp',
    auth: [oauth('Sign in with Mixpanel')],
    website: 'https://mixpanel.com',
    privacy: 'https://mixpanel.com/legal/privacy-policy/',
    source: 'https://developer.mixpanel.com/docs/mcp',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    summary: 'Product analytics, insights and feature flags.',
    category: 'analytics',
    endpointUrl: 'https://mcp.posthog.com/mcp',
    auth: [oauth('Sign in with PostHog')],
    website: 'https://posthog.com',
    privacy: 'https://posthog.com/privacy',
    source: 'https://posthog.com/docs/model-context-protocol',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    summary: 'Metrics, logs, dashboards and monitoring.',
    category: 'analytics',
    endpointUrl: 'https://mcp.datadoghq.com/v1/mcp',
    auth: [oauth('Sign in with Datadog')],
    website: 'https://datadoghq.com',
    privacy: 'https://www.datadoghq.com/legal/privacy/',
    source: 'https://docs.datadoghq.com/bits_ai/mcp_server/',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    summary: 'Incidents, on-call schedules and services.',
    category: 'analytics',
    endpointUrl: 'https://mcp.pagerduty.com/mcp',
    auth: [oauth('Sign in with PagerDuty')],
    website: 'https://pagerduty.com',
    privacy: 'https://www.pagerduty.com/privacy-policy/',
    source: 'https://developer.pagerduty.com/docs/mcp',
  },
  {
    id: 'thoughtspot',
    name: 'ThoughtSpot',
    summary: 'Analytics and BI search across your data.',
    category: 'analytics',
    endpointUrl: 'https://agent.thoughtspot.app/mcp',
    auth: [oauth('Sign in with ThoughtSpot')],
    website: 'https://thoughtspot.com',
    privacy: 'https://www.thoughtspot.com/privacy-policy',
    source: 'https://developers.thoughtspot.com/docs/mcp',
  },
  // ── Search / scraping / AI ───────────────────────────────────────────────
  {
    id: 'exa',
    name: 'Exa',
    summary: 'Web search, code search and page fetching tuned for agents.',
    category: 'search',
    endpointUrl: 'https://mcp.exa.ai/mcp',
    auth: [NONE, bearer('Exa API key', 'https://dashboard.exa.ai/api-keys')],
    website: 'https://exa.ai',
    privacy: 'https://exa.ai/privacy',
    source: 'https://docs.exa.ai/reference/exa-mcp',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    summary: 'Connect your AI agents to real-time web search.',
    category: 'search',
    endpointUrl: 'https://mcp.tavily.com/mcp/',
    auth: [bearer('Tavily API key', 'https://app.tavily.com/home')],
    website: 'https://tavily.com',
    privacy: 'https://tavily.com/privacy',
    source: 'https://docs.tavily.com/documentation/mcp',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    summary: 'Real-time web search and answer synthesis.',
    category: 'search',
    endpointUrl: 'https://api.perplexity.ai/mcp',
    auth: [bearer('Perplexity API key', 'https://www.perplexity.ai/settings/api')],
    website: 'https://perplexity.ai',
    privacy: 'https://www.perplexity.ai/hub/legal/privacy-policy',
    source: 'https://docs.perplexity.ai/guides/mcp-server',
  },
  {
    id: 'context7',
    name: 'Context7',
    summary: 'Up-to-date, version-specific library documentation.',
    category: 'search',
    endpointUrl: 'https://mcp.context7.com/mcp',
    auth: [NONE, bearer('Context7 API key', 'https://context7.com/dashboard')],
    website: 'https://context7.com',
    privacy: 'https://upstash.com/trust/privacy.pdf',
    source: 'https://github.com/upstash/context7',
  },
  {
    id: 'deepwiki',
    name: 'DeepWiki',
    summary: 'Ask questions against generated wikis for public GitHub repos.',
    category: 'search',
    endpointUrl: 'https://mcp.deepwiki.com/mcp',
    auth: [NONE],
    website: 'https://deepwiki.com',
    privacy: 'https://deepwiki.com/privacy',
    source: 'https://docs.devin.ai/work-with-devin/deepwiki-mcp',
  },
  {
    id: 'kagi',
    name: 'Kagi Search',
    summary: 'Private, ad-free web search.',
    category: 'search',
    endpointUrl: 'https://mcp.kagi.com/mcp',
    auth: [bearer('Kagi API key', 'https://kagi.com/settings?p=api')],
    website: 'https://kagi.com',
    privacy: 'https://kagi.com/privacy',
    source: 'https://help.kagi.com/kagi/api/mcp.html',
  },
  {
    id: 'brightdata',
    name: 'Bright Data',
    summary: 'Web scraping, search and structured data extraction.',
    category: 'scraping',
    endpointUrl: 'https://mcp.brightdata.com/mcp',
    auth: [bearer('Bright Data API token', 'https://brightdata.com/cp/setting/users')],
    website: 'https://brightdata.com',
    privacy: 'https://brightdata.com/legal/privacy',
    source: 'https://docs.brightdata.com/ai/mcp-server/overview',
  },
  {
    id: 'apify',
    name: 'Apify',
    summary: 'Web scraping and automation Actors.',
    category: 'scraping',
    endpointUrl: 'https://mcp.apify.com/mcp',
    auth: [
      oauth('Sign in with Apify'),
      bearer('Apify API token', 'https://console.apify.com/account/integrations'),
    ],
    website: 'https://apify.com',
    privacy: 'https://apify.com/privacy-policy',
    source: 'https://docs.apify.com/platform/integrations/mcp',
  },
  {
    id: 'simplescraper',
    name: 'SimpleScraper',
    summary: 'Scrape and structure web content.',
    category: 'scraping',
    endpointUrl: 'https://mcp.simplescraper.io/mcp',
    auth: [bearer('SimpleScraper API key', 'https://simplescraper.io')],
    website: 'https://simplescraper.io',
    privacy: 'https://simplescraper.io/privacy',
    source: 'https://simplescraper.io/docs/mcp',
  },
  {
    id: 'globalping',
    name: 'Globalping',
    summary: 'Network diagnostics from probes around the world.',
    category: 'scraping',
    endpointUrl: 'https://mcp.globalping.dev/mcp',
    auth: [NONE],
    website: 'https://globalping.io',
    privacy: 'https://www.jsdelivr.com/terms/privacy-policy',
    source: 'https://github.com/jsdelivr/globalping-mcp-server',
  },
  {
    id: 'composio',
    name: 'Composio',
    summary: 'Connect agents to hundreds of SaaS tools via one endpoint.',
    category: 'ai',
    endpointUrl: 'https://connect.composio.dev/mcp',
    auth: [oauth('Sign in with Composio')],
    website: 'https://composio.dev',
    privacy: 'https://composio.dev/privacy',
    source: 'https://docs.composio.dev/docs/mcp',
  },
  {
    id: 'fal',
    name: 'fal.ai',
    summary: 'Generate images and video with fal.ai models.',
    category: 'ai',
    endpointUrl: 'https://docs.fal.ai/mcp',
    auth: [bearer('fal.ai API key', 'https://fal.ai/dashboard/keys')],
    website: 'https://fal.ai',
    privacy: 'https://fal.ai/privacy',
    source: 'https://docs.fal.ai/mcp',
  },
  // ── Finance ──────────────────────────────────────────────────────────────
  {
    id: 'stripe',
    name: 'Stripe',
    summary: 'Payments, customers, subscriptions and invoices.',
    category: 'finance',
    endpointUrl: 'https://mcp.stripe.com',
    auth: [
      oauth('Sign in with Stripe'),
      bearer('Restricted API key', 'https://dashboard.stripe.com/apikeys'),
    ],
    website: 'https://stripe.com',
    privacy: 'https://stripe.com/privacy',
    source: 'https://docs.stripe.com/mcp',
  },
  {
    id: 'paypal',
    name: 'PayPal',
    summary: 'Invoices, orders and transactions from your PayPal account.',
    category: 'finance',
    endpointUrl: 'https://mcp.paypal.com/mcp',
    auth: [oauth('Sign in with PayPal')],
    website: 'https://paypal.com',
    privacy: 'https://www.paypal.com/us/legalhub/privacy-full',
    source: 'https://developer.paypal.com/docs/mcp/',
  },
  {
    id: 'square',
    name: 'Square',
    summary: 'Payments, orders, catalog and customers.',
    category: 'finance',
    endpointUrl: 'https://mcp.squareup.com/mcp',
    auth: [oauth('Sign in with Square')],
    website: 'https://squareup.com',
    privacy: 'https://squareup.com/us/en/legal/general/privacy',
    source: 'https://developer.squareup.com/docs/mcp',
  },
  {
    id: 'plaid',
    name: 'Plaid',
    summary: 'Financial data, accounts and transactions.',
    category: 'finance',
    endpointUrl: 'https://api.dashboard.plaid.com/mcp/sse',
    auth: [oauth('Sign in with Plaid')],
    website: 'https://plaid.com',
    privacy: 'https://plaid.com/legal/#privacy-statement',
    source: 'https://plaid.com/docs/mcp/',
  },
  // ── Productivity: files ──────────────────────────────────────────────────
  {
    id: 'box',
    name: 'Box',
    summary: 'Search and read documents and folders in your Box account.',
    category: 'productivity',
    endpointUrl: 'https://mcp.box.com',
    auth: [oauth('Sign in with Box')],
    website: 'https://box.com',
    privacy: 'https://www.box.com/legal/privacypolicy',
    source: 'https://developer.box.com/guides/box-mcp/',
  },
  {
    id: 'egnyte',
    name: 'Egnyte',
    summary: 'Enterprise file sharing and content search.',
    category: 'productivity',
    endpointUrl: 'https://mcp-server.egnyte.com/mcp',
    auth: [oauth('Sign in with Egnyte')],
    website: 'https://egnyte.com',
    privacy: 'https://www.egnyte.com/privacy-policy',
    source: 'https://developers.egnyte.com/docs/mcp',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    summary: 'Search, read and draft email in your Gmail mailbox.',
    category: 'productivity',
    endpointUrl: 'https://gmailmcp.googleapis.com/mcp/v1',
    auth: [oauth('Sign in with Google')],
    website: 'https://workspace.google.com/products/gmail/',
    privacy: 'https://policies.google.com/privacy',
    source: 'https://developers.google.com/workspace/gmail/api/guides/configure-mcp-server',
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    summary: 'Search, read and manage files in Google Drive.',
    category: 'productivity',
    endpointUrl: 'https://drivemcp.googleapis.com/mcp/v1',
    auth: [oauth('Sign in with Google')],
    website: 'https://drive.google.com',
    privacy: 'https://policies.google.com/privacy',
    source: 'https://developers.google.com/workspace/drive/api/guides/configure-mcp-server',
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    summary: 'Read and edit documents in Google Docs.',
    category: 'productivity',
    endpointUrl: 'https://docsmcp.googleapis.com/mcp/v1',
    auth: [oauth('Sign in with Google')],
    website: 'https://docs.google.com',
    privacy: 'https://policies.google.com/privacy',
    source: 'https://developers.google.com/workspace/docs/api/guides/configure-mcp-server',
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    summary: 'Read and update spreadsheets in Google Sheets.',
    category: 'productivity',
    endpointUrl: 'https://sheetsmcp.googleapis.com/mcp/v1',
    auth: [oauth('Sign in with Google')],
    website: 'https://sheets.google.com',
    privacy: 'https://policies.google.com/privacy',
    source: 'https://developers.google.com/workspace/sheets/api/guides/configure-mcp-server',
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    summary: 'Read and manage events in Google Calendar.',
    category: 'productivity',
    endpointUrl: 'https://calendarmcp.googleapis.com/mcp/v1',
    auth: [oauth('Sign in with Google')],
    website: 'https://calendar.google.com',
    privacy: 'https://policies.google.com/privacy',
    source: 'https://developers.google.com/workspace/calendar/api/guides/configure-mcp-server',
  },
  // ── Lifestyle ────────────────────────────────────────────────────────────
  {
    id: 'strava',
    name: 'Strava',
    summary: 'Your activities, stats and training data.',
    category: 'lifestyle',
    endpointUrl: 'https://mcp.strava.com/mcp',
    auth: [oauth('Sign in with Strava')],
    website: 'https://strava.com',
    privacy: 'https://www.strava.com/legal/privacy',
    source: 'https://developers.strava.com/docs/mcp/',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    summary: 'Music and podcast discovery, recommendations and playback.',
    category: 'lifestyle',
    endpointUrl: 'https://mcp.spotify.com/mcp',
    auth: [oauth('Sign in with Spotify')],
    website: 'https://spotify.com',
    privacy: 'https://www.spotify.com/legal/privacy-policy/',
    source: 'https://developer.spotify.com/documentation/mcp',
  },
  {
    id: 'ticket-tailor',
    name: 'Ticket Tailor',
    summary: 'Manage event tickets, orders and attendees.',
    category: 'lifestyle',
    endpointUrl: 'https://mcp.tickettailor.com/mcp',
    auth: [bearer('Ticket Tailor API key', 'https://dashboard.tickettailor.com/settings/api')],
    website: 'https://tickettailor.com',
    privacy: 'https://www.tickettailor.com/privacy-policy',
    source: 'https://developers.tickettailor.com/docs/mcp',
  },
];

/** Fast lookup by plugin id. */
export const mcpCatalogById: ReadonlyMap<string, McpCatalogEntry> = new Map(
  mcpServerCatalog.map((entry) => [entry.id, entry]),
);
