import type { PdfResourceIndex } from '@cherrystudio/file-preview-webview/protocol';
import { useQuery } from '@tanstack/react-query';
import { Asset } from 'expo-asset';
import { File } from 'expo-file-system';

import { queryKeys } from '@/frontend/data';

// Generated by `@cherrystudio/file-preview-webview` on install; see its README.
const PAGE_ASSET = require('@cherrystudio/file-preview-webview/file-preview.html');
// eslint-disable-next-line @typescript-eslint/no-require-imports -- Metro asset; `bin` is registered in metro.config.js
const PDF_RESOURCES_ASSET = require('@cherrystudio/file-preview-webview/pdf-resources.bin');
const PDF_RESOURCE_INDEX: PdfResourceIndex = require('@cherrystudio/file-preview-webview/pdf-resources.json');

export interface DocumentPreviewPage {
  html: string;
  pdfResources: { uri: string; index: PdfResourceIndex };
}

async function loadDocumentPreviewPage(): Promise<DocumentPreviewPage> {
  const [page, pdfResources] = await Asset.loadAsync([PAGE_ASSET, PDF_RESOURCES_ASSET]);
  if (!page?.localUri || !pdfResources?.localUri) {
    throw new Error('Document preview assets are unavailable');
  }
  return {
    html: await new File(page.localUri).text(),
    pdfResources: { uri: pdfResources.localUri, index: PDF_RESOURCE_INDEX },
  };
}

/** The bundled preview page, kept for one minute after the last viewer closes. */
export function useDocumentPreviewPage() {
  return useQuery({
    gcTime: 60_000,
    networkMode: 'always',
    queryFn: loadDocumentPreviewPage,
    queryKey: queryKeys.files.documentPreviewPage(),
    retry: false,
    staleTime: Infinity,
  });
}
